# Generated by Django 4.0.3 on 2022-04-06 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_id_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Exactly 12 digits is allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
