# Generated by Django 4.0.3 on 2022-04-04 07:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(400)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(400)])),
                ('main_colors', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'black'), (2, 'blue'), (3, 'brown'), (4, 'gray'), (5, 'green'), (6, 'orange'), (7, 'pink'), (8, 'purple'), (9, 'red'), (10, 'white'), (11, 'yellow'), (12, 'all')], default='all', max_length=26)),
                ('likes', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
