# Generated by Django 4.0.3 on 2022-04-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='photo',
            field=models.ImageField(default=1, upload_to='paintings_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='art_portal_app.style'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='techniques',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='art_portal_app.technique'),
            preserve_default=False,
        ),
    ]
