# Generated by Django 4.0.3 on 2022-04-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0003_rename_style_name_technique_technique_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['style_name']},
        ),
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ['technique_name']},
        ),
    ]
