# Generated by Django 4.0.3 on 2022-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0005_gallery_painting_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
