# Generated by Django 4.0.3 on 2022-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0006_alter_gallery_options_alter_gallery_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='painting',
            name='base_material',
            field=models.CharField(choices=[(1, 'canvas'), (2, 'paper'), (3, 'wood'), (4, 'glass'), (5, 'metal')], default='canvas', max_length=6),
        ),
    ]
