# Generated by Django 4.0.3 on 2022-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0008_alter_painting_base_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='base_material',
            field=models.CharField(choices=[('Canvas', 'Canvas'), ('Paper', 'Paper'), ('Wood', 'Wood'), ('Glass', 'Glass'), ('Metal', 'Metal')], default='Canvas', max_length=6),
        ),
    ]
