# Generated by Django 4.0.3 on 2022-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0009_alter_painting_base_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(blank=True, default='Unnamed', max_length=50, null=True),
        ),
    ]
