# Generated by Django 4.0.3 on 2022-04-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0010_alter_painting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
