# Generated by Django 4.0.3 on 2022-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_portal_app', '0011_painting_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['likes']},
        ),
    ]
